version: '3.7'
services:
  dbos:   
    image: mysql:5.7
    volumes:
      - wpdb_vl:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ks
      MYSQL_USER: kush
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb
        
  wpos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: kush
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wp_vl:/var/www/html

volumes:
   wp_vl:
   wpdb_vl:
   

